services:
  # === Microservices ===

  movie_service:
    build:
      context: ./movie_service
      dockerfile: Dockerfile
    container_name: cinesync_movie_service
    ports:
      - "8001:8000"  # 8001 на хосте -> 8000 в контейнере
    env_file:
      - ./movie_service/.env
    environment:
      # Переопределяем хост Redis для внутренней сети Docker
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - cinesync_net

  # === Infrastructure ===

  postgres:
    image: postgres:16-alpine
    container_name: cinesync_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: cinesync_default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinesync_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cinesync_redis
    ports:
      - "6379:6379"
    networks:
      - cinesync_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cinesync_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cinesync_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  cinesync_net:
    driver: bridge